using UnityEngine;

/// <summary>
/// Procedural rain curtain generated by code.
/// No Shader Graph, no texture, no particle system.
/// Good for window rain sheet / distant rain sheet in VR scenes.
/// </summary>
[RequireComponent(typeof(MeshFilter))]
[RequireComponent(typeof(MeshRenderer))]
public class ProceduralRainCurtain : MonoBehaviour
{
    [Header("Rain Area")]
    [Tooltip("Width of the rain curtain in local space.")]
    public float width = 6f;

    [Tooltip("Height of the rain curtain in local space.")]
    public float height = 3f;

    [Header("Rain Streaks")]
    [Range(10, 2000)]
    public int maxStreaks = 300;

    [Range(0f, 1f)]
    public float rainIntensity = 0.5f;

    public float minLength = 0.25f;
    public float maxLength = 0.75f;

    public float minLineWidth = 0.008f;
    public float maxLineWidth = 0.02f;

    public float minFallSpeed = 1.5f;
    public float maxFallSpeed = 6f;

    [Tooltip("Horizontal slant of rain streaks. Negative means leaning left.")]
    public float slant = -0.08f;

    [Header("Visual")]
    public Color rainColor = new Color(0.75f, 0.85f, 1f, 0.35f);

    [Tooltip("Max alpha when rainIntensity = 1.")]
    [Range(0f, 1f)]
    public float maxAlpha = 0.45f;

    [Tooltip("Brightness multiplier.")]
    public float brightness = 1f;

    [Header("Runtime Smoothing")]
    public bool smoothIntensity = true;
    public float intensityChangeSpeed = 2f;

    [Range(0f, 1f)]
    public float targetIntensity = 0.5f;

    private Mesh mesh;
    private MeshRenderer meshRenderer;
    private MaterialPropertyBlock propertyBlock;

    private Vector3[] vertices;
    private Vector2[] uvs;
    private int[] allTriangles;
    private int[] activeTriangles;

    private float[] posX;
    private float[] posY;
    private float[] lengths;
    private float[] lineWidths;
    private float[] speeds;
    private float[] localSlants;

    private int currentActiveCount = -1;

    private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");

    private void Awake()
    {
        Initialize();
        ApplyIntensityImmediate(rainIntensity);
    }

    private void OnEnable()
    {
        if (mesh == null)
        {
            Initialize();
        }
    }

    private void Update()
    {
        if (smoothIntensity)
        {
            rainIntensity = Mathf.MoveTowards(
                rainIntensity,
                targetIntensity,
                intensityChangeSpeed * Time.deltaTime
            );
        }

        UpdateActiveCount();
        UpdateRainPositions(Time.deltaTime);
        UpdateMaterial();
    }

    private void OnValidate()
    {
        width = Mathf.Max(0.01f, width);
        height = Mathf.Max(0.01f, height);
        maxStreaks = Mathf.Max(10, maxStreaks);
        maxLength = Mathf.Max(minLength, maxLength);
        maxLineWidth = Mathf.Max(minLineWidth, maxLineWidth);

        if (Application.isPlaying)
        {
            Initialize();
            ApplyIntensityImmediate(rainIntensity);
        }
    }

    public void SetRainIntensity(float value)
    {
        targetIntensity = Mathf.Clamp01(value);

        if (!smoothIntensity)
        {
            ApplyIntensityImmediate(targetIntensity);
        }
    }

    public void ApplyIntensityImmediate(float value)
    {
        rainIntensity = Mathf.Clamp01(value);
        targetIntensity = rainIntensity;
        UpdateActiveCount();
        UpdateMaterial();
    }

    public void StopRain()
    {
        SetRainIntensity(0f);
    }

    public void LightRain()
    {
        SetRainIntensity(0.25f);
    }

    public void MediumRain()
    {
        SetRainIntensity(0.55f);
    }

    public void HeavyRain()
    {
        SetRainIntensity(0.85f);
    }

    private void Initialize()
    {
        meshRenderer = GetComponent<MeshRenderer>();
        propertyBlock = new MaterialPropertyBlock();

        mesh = new Mesh();
        mesh.name = "Procedural_Rain_Curtain_Mesh";
        mesh.MarkDynamic();

        GetComponent<MeshFilter>().sharedMesh = mesh;

        vertices = new Vector3[maxStreaks * 4];
        uvs = new Vector2[maxStreaks * 4];
        allTriangles = new int[maxStreaks * 6];

        posX = new float[maxStreaks];
        posY = new float[maxStreaks];
        lengths = new float[maxStreaks];
        lineWidths = new float[maxStreaks];
        speeds = new float[maxStreaks];
        localSlants = new float[maxStreaks];

        for (int i = 0; i < maxStreaks; i++)
        {
            ResetStreak(i, true);

            int v = i * 4;
            int t = i * 6;

            uvs[v + 0] = new Vector2(0, 0);
            uvs[v + 1] = new Vector2(1, 0);
            uvs[v + 2] = new Vector2(0, 1);
            uvs[v + 3] = new Vector2(1, 1);

            allTriangles[t + 0] = v + 0;
            allTriangles[t + 1] = v + 2;
            allTriangles[t + 2] = v + 1;
            allTriangles[t + 3] = v + 2;
            allTriangles[t + 4] = v + 3;
            allTriangles[t + 5] = v + 1;
        }

        mesh.vertices = vertices;
        mesh.uv = uvs;

        currentActiveCount = -1;
        UpdateActiveCount();
        UpdateRainPositions(0f);

        mesh.RecalculateBounds();
    }

    private void ResetStreak(int i, bool randomY)
    {
        posX[i] = Random.Range(-width * 0.5f, width * 0.5f);
        posY[i] = randomY
            ? Random.Range(-height * 0.5f, height * 0.5f)
            : height * 0.5f + Random.Range(0f, height * 0.2f);

        lengths[i] = Random.Range(minLength, maxLength);
        lineWidths[i] = Random.Range(minLineWidth, maxLineWidth);
        speeds[i] = Random.Range(minFallSpeed, maxFallSpeed);
        localSlants[i] = slant * Random.Range(0.6f, 1.4f);
    }

    private void UpdateActiveCount()
    {
        int activeCount = Mathf.RoundToInt(maxStreaks * rainIntensity);

        if (activeCount == currentActiveCount)
            return;

        currentActiveCount = activeCount;

        if (activeCount <= 0)
        {
            mesh.triangles = System.Array.Empty<int>();
            return;
        }

        int triangleCount = activeCount * 6;
        activeTriangles = new int[triangleCount];
        System.Array.Copy(allTriangles, activeTriangles, triangleCount);

        mesh.triangles = activeTriangles;
        mesh.RecalculateBounds();
    }

    private void UpdateRainPositions(float deltaTime)
    {
        if (currentActiveCount <= 0)
            return;

        float intensitySpeedMultiplier = Mathf.Lerp(0.7f, 1.4f, rainIntensity);

        for (int i = 0; i < currentActiveCount; i++)
        {
            posY[i] -= speeds[i] * intensitySpeedMultiplier * deltaTime;

            if (posY[i] < -height * 0.5f - lengths[i])
            {
                ResetStreak(i, false);
            }

            WriteStreakVertices(i);
        }

        mesh.vertices = vertices;
    }

    private void WriteStreakVertices(int i)
    {
        int v = i * 4;

        float x = posX[i];
        float yTop = posY[i];
        float yBottom = posY[i] - lengths[i];

        float halfWidth = lineWidths[i] * 0.5f;
        float xBottom = x + localSlants[i];

        // Local XY plane, Z = 0.
        vertices[v + 0] = new Vector3(x - halfWidth, yTop, 0f);
        vertices[v + 1] = new Vector3(x + halfWidth, yTop, 0f);
        vertices[v + 2] = new Vector3(xBottom - halfWidth, yBottom, 0f);
        vertices[v + 3] = new Vector3(xBottom + halfWidth, yBottom, 0f);
    }

    private void UpdateMaterial()
    {
        if (meshRenderer == null)
            return;

        Color c = rainColor;
        c.r *= brightness;
        c.g *= brightness;
        c.b *= brightness;
        c.a = maxAlpha * rainIntensity;

        meshRenderer.GetPropertyBlock(propertyBlock);
        propertyBlock.SetColor(BaseColorId, c);
        meshRenderer.SetPropertyBlock(propertyBlock);
    }

    private void OnDrawGizmosSelected()
    {
        Gizmos.color = new Color(0.3f, 0.6f, 1f, 0.4f);
        Gizmos.matrix = transform.localToWorldMatrix;
        Gizmos.DrawWireCube(Vector3.zero, new Vector3(width, height, 0.01f));
    }
}